In [17]:
def count_speed(speed,ice_rate):
    return speed*(1-ice_rate*0.07)

In [18]:
import numpy as np
icebreakers = np.load('icebreakers.npy')
icebreakers

array([['50 лет Победы', '9152959'],
       ['Ямал', '9077549'],
       ['Таймыр', '8417481'],
       ['Вайгач', '8417493']], dtype='<U13')

In [19]:
applications = np.load('applications.npy')
applications

array([['Штурман Альбанов', '9752084', 'Arc7', '15',
        'точка в Баренцевом море', 'Саббета 3', '01.01.21 23:30',
        '05.01.21 5:00'],
       ['Штурман Альбанов', '9752084', 'Arc7', '15', 'Саббета 3',
        'точка в Баренцевом море', '06.01.21 11:00', '10.01.21 18:00'],
       ['Штурман Альбанов', '9752084', 'Arc7', '15',
        'точка в Баренцевом море', 'Саббета 3', '12.01.21 18:00',
        '16.01.21 22:00'],
       ['Штурман Альбанов', '9752084', 'Arc7', '15', 'Саббета 3',
        'точка в Баренцевом море', '17.01.21 6:00', '21.01.21 20:45'],
       ['Штурман Альбанов', '9752084', 'Arc7', '15',
        'точка в Баренцевом море', 'Саббета 3', '21.01.21 9:00',
        '26.01.21 22:00'],
       ['Штурман Альбанов', '9752084', 'Arc7', '15', 'Саббета 3',
        'точка в Баренцевом море', '28.01.21 1:00', '02.02.21 19:00'],
       ['Штурман Кошелев', '9759939', 'Arc7', '15', 'Саббета 3',
        'точка в Баренцевом море', '02.01.21 20:30', '06.01.21 7:00'],
       ['Штурман

In [20]:
ice_concentration = np.load('monthly_ice_concentration.npy')
ice_concentration

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 2],
       [0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4, 4, 4, 5, 5, 5],
       [1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
        5, 5, 5, 5, 6, 6, 6, 6],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 2, 2],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
        4, 4, 4, 4, 4, 5, 5, 6],
       [1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
        5, 5, 6, 6, 6, 6, 6, 7],
       [1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5,
        5, 6, 6, 6, 6, 6, 7, 7],
       [2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6,
        7, 7, 7, 7, 7, 8, 8, 8],
       [2, 2, 2, 3, 3, 3, 3, 4, 4, 4,

In [21]:
rib_accessibility = np.load('rib_accessibility.npy')
rib_accessibility

array([[ 1,  1,  1,  1,  1],
       [ 2,  1,  1,  1,  1],
       [ 3,  1,  1,  1,  1],
       [ 4,  1,  1,  1,  1],
       [ 5,  1,  1,  1,  1],
       [ 6,  1,  1,  1,  1],
       [ 7,  1,  1,  1,  1],
       [ 8,  1,  1,  1,  1],
       [ 9,  1,  1,  1,  1],
       [10,  1,  1,  1,  1],
       [11,  1,  1,  1,  1],
       [12,  1,  1,  1,  1],
       [13,  1,  1,  1,  1],
       [14,  0,  0,  1,  1]], dtype=int64)

In [22]:
data_miles = np.load('data_miles.npy')
data_miles

array([802.38447757, 594.25408908, 370.12977626, 672.22982867,
       962.41301457, 201.99509623, 111.74134535,  62.52612185,
        76.98144452,  27.755861  ,  27.4565565 ,  50.74126274,
        27.07280231,  47.85292243])

In [23]:
import random as random # Импортируем библиотку генерации случайных значений
import numpy as np # Импортируем библиотеку numpy
import matplotlib.pyplot as plt # Импортируем модуль pyplot библиотеки matplotlib
import matplotlib.colors as colors # Импортируем модуль colors библиотеки matplotlib

# Статический вывод графики (графики отображаются в той ячейке, в которой используется plt.show())
%matplotlib inline 

In [63]:
'''
    тут показаны из какой вершины можно попасть в какую, 
    если можно, то вместо 0 ставится номер графа, по которому это можно сделать
'''
graph_of_path = [ 
    [ 0, 1, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 3, 0, 6, 0, 7, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 6, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 8, 0, 9, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 9, 0,10, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0,10, 0,11,12, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0,11, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0,12, 0, 0,13,14],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,13, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,14, 0, 0]]

graph_with_lengths=[]
for i in range(14):
    a=[]
    for j in range(14):
        if(graph_of_path[i][j]):
            a.append(data_miles[graph_of_path[i][j]-1])
        else:
            a.append(0)
    graph_with_lengths.append(a)
    
graph_with_time=[]
speed = 15
for i in range(14):
    a=[]
    for j in range(14):
        a.append(graph_with_lengths[i][j]/count_speed(speed,ice_concentration[graph_of_path[i][j]-1][1]))
    graph_with_time.append(a)
graph_with_time

[[0.0,
  53.492298504880274,
  0.0,
  0.0,
  0.0,
  44.81532191100501,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [53.492298504880274,
  0.0,
  42.598859432057665,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [0.0,
  42.598859432057665,
  0.0,
  26.532600448888054,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [0.0,
  0.0,
  26.532600448888054,
  0.0,
  13.466339748671427,
  0.0,
  8.010132283093665,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [0.0,
  0.0,
  0.0,
  13.466339748671427,
  0.0,
  64.16086763769641,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [44.81532191100501,
  0.0,
  0.0,
  0.0,
  64.16086763769641,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [0.0,
  0.0,
  0.0,
  8.010132283093665,
  0.0,
  0.0,
  0.0,
  4.482159272577812,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 [0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  4.482159272577812,
  0.0,
  5.967553839139009

In [64]:
class Graph():
 
    def __init__(self, vertices):
        self.V = vertices
        self.graph = [[0 for column in range(vertices)]
                      for row in range(vertices)]
 
    def printSolution(self, dist):
        print("Vertex \t Distance from Source")
        for node in range(self.V):
            print(node, "\t\t", dist[node])
 
    # A utility function to find the vertex with
    # minimum distance value, from the set of vertices
    # not yet included in shortest path tree
    def minDistance(self, dist, sptSet):
 
        # Initialize minimum distance for next node
        min = 1e7
 
        # Search not nearest vertex not in the
        # shortest path tree
        for v in range(self.V):
            if dist[v] < min and sptSet[v] == False:
                min = dist[v]
                min_index = v
 
        return min_index
 
    # Function that implements Dijkstra's single source
    # shortest path algorithm for a graph represented
    # using adjacency matrix representation
    def dijkstra(self, src):
 
        dist = [1e7] * self.V
        dist[src] = 0
        sptSet = [False] * self.V
 
        for cout in range(self.V):
 
            # Pick the minimum distance vertex from
            # the set of vertices not yet processed.
            # u is always equal to src in first iteration
            u = self.minDistance(dist, sptSet)
 
            # Put the minimum distance vertex in the
            # shortest path tree
            sptSet[u] = True
 
            # Update dist value of the adjacent vertices
            # of the picked vertex only if the current
            # distance is greater than new distance and
            # the vertex in not in the shortest path tree
            for v in range(self.V):
                if (self.graph[u][v] > 0 and
                   sptSet[v] == False and
                   dist[v] > dist[u] + self.graph[u][v]):
                    dist[v] = dist[u] + self.graph[u][v]
         
        self.printSolution(dist)
        return dist
 
# Driver program
g = Graph(14)
g.graph = graph_with_time
 
dist_of_ways = g.dijkstra(3)

Vertex 	 Distance from Source
0 		 122.44252929737286
1 		 69.13145988094573
2 		 26.532600448888054
3 		 0
4 		 13.466339748671427
5 		 77.62720738636784
6 		 8.010132283093665
7 		 12.492291555671477
8 		 18.459845394810486
9 		 20.611462526895572
10 		 22.928471514154765
11 		 24.89342562749325
12 		 27.178050294754442
13 		 28.93164693000113


In [55]:
speed = 15
dist_of_ways[0]/9

196.30759365693297