In [394]:
def count_speed(speed,ice_rate):
    if (ice_rate==0 ): return speed
    return speed*(1-ice_rate*0.07)

In [290]:
import numpy as np
icebreakers = np.load('icebreakers.npy')
icebreakers

array([['50 лет Победы', '9152959'],
       ['Ямал', '9077549'],
       ['Таймыр', '8417481'],
       ['Вайгач', '8417493']], dtype='<U13')

In [291]:
applications = np.load('applications.npy')
applications

array([['Штурман Альбанов', '9752084', 'Arc7', '15',
        'точка в Баренцевом море', 'Саббета 3', '01.01.21 23:30',
        '05.01.21 5:00'],
       ['Штурман Альбанов', '9752084', 'Arc7', '15', 'Саббета 3',
        'точка в Баренцевом море', '06.01.21 11:00', '10.01.21 18:00'],
       ['Штурман Альбанов', '9752084', 'Arc7', '15',
        'точка в Баренцевом море', 'Саббета 3', '12.01.21 18:00',
        '16.01.21 22:00'],
       ['Штурман Альбанов', '9752084', 'Arc7', '15', 'Саббета 3',
        'точка в Баренцевом море', '17.01.21 6:00', '21.01.21 20:45'],
       ['Штурман Альбанов', '9752084', 'Arc7', '15',
        'точка в Баренцевом море', 'Саббета 3', '21.01.21 9:00',
        '26.01.21 22:00'],
       ['Штурман Альбанов', '9752084', 'Arc7', '15', 'Саббета 3',
        'точка в Баренцевом море', '28.01.21 1:00', '02.02.21 19:00'],
       ['Штурман Кошелев', '9759939', 'Arc7', '15', 'Саббета 3',
        'точка в Баренцевом море', '02.01.21 20:30', '06.01.21 7:00'],
       ['Штурман

In [384]:
ice_concentration = list(np.load('monthly_ice_concentration.npy'))
ice_concentration

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 2], dtype=int64),
 array([0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4, 4, 4, 5, 5, 5], dtype=int64),
 array([1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
        5, 5, 5, 5, 6, 6, 6, 6], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 2], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
        4, 4, 4, 4, 4, 5, 5, 6], dtype=int64),
 array([1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
        5, 5, 6, 6, 6, 6, 6, 7], dtype=int64),
 array([1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5,
        5, 6, 6, 6, 6, 6, 7, 7], dtype=int64),
 array([2, 2, 2, 2, 3, 3, 3, 3, 

In [293]:
rib_accessibility = np.load('rib_accessibility.npy')
rib_accessibility

array([[ 1,  1,  1,  1,  1],
       [ 2,  1,  1,  1,  1],
       [ 3,  1,  1,  1,  1],
       [ 4,  1,  1,  1,  1],
       [ 5,  1,  1,  1,  1],
       [ 6,  1,  1,  1,  1],
       [ 7,  1,  1,  1,  1],
       [ 8,  1,  1,  1,  1],
       [ 9,  1,  1,  1,  1],
       [10,  1,  1,  1,  1],
       [11,  1,  1,  1,  1],
       [12,  1,  1,  1,  1],
       [13,  1,  1,  1,  1],
       [14,  0,  0,  1,  1]], dtype=int64)

In [294]:
data_miles = np.load('data_miles.npy')
data_miles

array([802.38447757, 594.25408908, 370.12977626, 672.22982867,
       962.41301457, 201.99509623, 111.74134535,  62.52612185,
        76.98144452,  27.755861  ,  27.4565565 ,  50.74126274,
        27.07280231,  47.85292243])

In [295]:
import random as random # Импортируем библиотку генерации случайных значений
import numpy as np # Импортируем библиотеку numpy
import matplotlib.pyplot as plt # Импортируем модуль pyplot библиотеки matplotlib
import matplotlib.colors as colors # Импортируем модуль colors библиотеки matplotlib

# Статический вывод графики (графики отображаются в той ячейке, в которой используется plt.show())
%matplotlib inline 

In [296]:
'''
    тут показаны из какой вершины можно попасть в какую, 
    если можно, то вместо 0 ставится номер графа, по которому это можно сделать
'''
graph_of_path = [ 
    [ 0, 1, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 3, 0, 6, 0, 7, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 6, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 4, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 8, 0, 9, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 9, 0,10, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0,10, 0,11,12, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0,11, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0,12, 0, 0,13,14],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,13, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,14, 0, 0]]

graph_with_lengths=[]
for i in range(14):
    a=[]
    for j in range(14):
        if(graph_of_path[i][j]):
            a.append(data_miles[graph_of_path[i][j]-1])
        else:
            a.append(0)
    graph_with_lengths.append(a)

In [441]:
class Graph():
 
    def __init__(self, vertices):
        self.V = vertices
        self.graph = [[0 for column in range(vertices)]
                      for row in range(vertices)]
 
    def printSolution(self, dist):
        print("Vertex \t Distance from Source")
        for node in range(self.V):
            print(node, "\t\t", dist[node])
 
    # A utility function to find the vertex with
    # minimum distance value, from the set of vertices
    # not yet included in shortest path tree
    def minDistance(self, dist, sptSet):
 
        # Initialize minimum distance for next node
        min = 1e7
        min_index = -1
        # Search not nearest vertex not in the
        # shortest path tree
        for v in range(self.V):
            if dist[v] < min and sptSet[v] == False:
                min = dist[v]
                min_index = v
 
        return min_index
 
    # Function that implements Dijkstra's single source
    # shortest path algorithm for a graph represented
    # using adjacency matrix representation
    def dijkstra(self, src):
 
        dist = [1e7] * self.V
        dist[src] = 0
        sptSet = [False] * self.V
 
        for cout in range(self.V):
 
            # Pick the minimum distance vertex from
            # the set of vertices not yet processed.
            # u is always equal to src in first iteration
            u = self.minDistance(dist, sptSet)
 
            # Put the minimum distance vertex in the
            # shortest path tree
            sptSet[u] = True
 
            # Update dist value of the adjacent vertices
            # of the picked vertex only if the current
            # distance is greater than new distance and
            # the vertex in not in the shortest path tree
            for v in range(self.V):
                if (self.graph[u][v] > 0 and
                   sptSet[v] == False and
                   dist[v] > dist[u] + self.graph[u][v]):
                    dist[v] = dist[u] + self.graph[u][v]
         
        self.printSolution(dist)
        return dist

In [442]:
speed = 15
dist_of_ways[0]/9

13.604725477485873

In [443]:
import pandas as pd

In [444]:
df_applapplications=pd.DataFrame()

In [445]:
df_applications = pd.DataFrame(applications,columns = ["Наименование","IMO","Ледовый класс","Скорость","Начало","Окончание","Дата и время начала","Дата и время окончания"])
df_applications.head()

Наименование      IMO Ледовый класс Скорость                   Начало  \
0  Штурман Альбанов  9752084          Arc7       15  точка в Баренцевом море   
1  Штурман Альбанов  9752084          Arc7       15                Саббета 3   
2  Штурман Альбанов  9752084          Arc7       15  точка в Баренцевом море   
3  Штурман Альбанов  9752084          Arc7       15                Саббета 3   
4  Штурман Альбанов  9752084          Arc7       15  точка в Баренцевом море   

                 Окончание Дата и время начала Дата и время окончания  
0                Саббета 3      01.01.21 23:30          05.01.21 5:00  
1  точка в Баренцевом море      06.01.21 11:00         10.01.21 18:00  
2                Саббета 3      12.01.21 18:00         16.01.21 22:00  
3  точка в Баренцевом море       17.01.21 6:00         21.01.21 20:45  
4                Саббета 3       21.01.21 9:00         26.01.21 22:00

In [446]:
df_applications = df_applications.drop("Наименование", axis=1)
df_applications.head()

IMO Ледовый класс Скорость                   Начало  \
0  9752084          Arc7       15  точка в Баренцевом море   
1  9752084          Arc7       15                Саббета 3   
2  9752084          Arc7       15  точка в Баренцевом море   
3  9752084          Arc7       15                Саббета 3   
4  9752084          Arc7       15  точка в Баренцевом море   

                 Окончание Дата и время начала Дата и время окончания  
0                Саббета 3      01.01.21 23:30          05.01.21 5:00  
1  точка в Баренцевом море      06.01.21 11:00         10.01.21 18:00  
2                Саббета 3      12.01.21 18:00         16.01.21 22:00  
3  точка в Баренцевом море       17.01.21 6:00         21.01.21 20:45  
4                Саббета 3       21.01.21 9:00         26.01.21 22:00

In [447]:
df_applications.loc[df_applications['Ледовый класс'] == "Arc7", 'Ледовый класс'] = 3
df_applications.loc[df_applications['Ледовый класс'] == "Arc8", 'Ледовый класс'] = 3
df_applications.loc[df_applications['Ледовый класс'] == "Arc9", 'Ледовый класс'] = 3

In [448]:
df_applications.loc[df_applications['Ледовый класс'] == "Arc4", 'Ледовый класс'] = 2
df_applications.loc[df_applications['Ледовый класс'] == "Arc5", 'Ледовый класс'] = 2
df_applications.loc[df_applications['Ледовый класс'] == "Arc6", 'Ледовый класс'] = 2

In [449]:
df_applications.loc[df_applications['Ледовый класс'] == "No ice class", 'Ледовый класс'] = 1
df_applications.loc[df_applications['Ледовый класс'] == "Ice1", 'Ледовый класс'] = 1
df_applications.loc[df_applications['Ледовый класс'] == "Ice2", 'Ледовый класс'] = 1
df_applications.loc[df_applications['Ледовый класс'] == "Ice3", 'Ледовый класс'] = 1

In [450]:
df_applications.describe()

IMO  Ледовый класс Скорость                   Начало  \
count        47             47       47                       47   
unique       17              3        6                        7   
top     9752084              3       15  точка в Баренцевом море   
freq          6             22       19                       24   

                      Окончание Дата и время начала Дата и время окончания  
count                        47                  47                     47  
unique                        6                  46                     46  
top     точка в Баренцевом море       23.01.21 0:30         26.01.21 22:00  
freq                         23                   2                      2

In [451]:
'''
Тег в таблице и индекс точки в нашем графе
точка в Баренцевом море - 0
Сабетта 1 - 13
Сабетта 2 - 12
Сабетта 3 - 10
'''

df_applications.loc[df_applications['Начало'] == "точка в Баренцевом море", 'Начало'] = 0
df_applications.loc[df_applications['Начало'] == "точка в Баренцевом море ", 'Начало'] = 0
df_applications.loc[df_applications['Начало'] == "Сабетта 1", 'Начало'] = 13
df_applications.loc[df_applications['Начало'] == "Сабетта 2", 'Начало'] = 12
df_applications.loc[df_applications['Начало'] == "Сабетта 3", 'Начало'] = 10
df_applications.loc[df_applications['Начало'] == "Сабетта 1 ", 'Начало'] = 13
df_applications.loc[df_applications['Начало'] == "Сабетта 2 ", 'Начало'] = 12
df_applications.loc[df_applications['Начало'] == "Сабетта 3 ", 'Начало'] = 10
df_applications.loc[df_applications['Начало'] == "Саббета 1", 'Начало'] = 13
df_applications.loc[df_applications['Начало'] == "Саббета 2", 'Начало'] = 12
df_applications.loc[df_applications['Начало'] == "Саббета 3", 'Начало'] = 10
df_applications.loc[df_applications['Начало'] == "Саббета 1 ", 'Начало'] = 13
df_applications.loc[df_applications['Начало'] == "Саббета 2 ", 'Начало'] = 12
df_applications.loc[df_applications['Начало'] == "Саббета 3 ", 'Начало'] = 10

df_applications.loc[df_applications['Окончание'] == "точка в Баренцевом море", 'Окончание'] = 0
df_applications.loc[df_applications['Окончание'] == "точка в Баренцевом море ", 'Окончание'] = 0
df_applications.loc[df_applications['Окончание'] == "Сабетта 1", 'Окончание'] = 13
df_applications.loc[df_applications['Окончание'] == "Сабетта 2", 'Окончание'] = 12
df_applications.loc[df_applications['Окончание'] == "Сабетта 3", 'Окончание'] = 10
df_applications.loc[df_applications['Окончание'] == "Сабетта 1 ", 'Окончание'] = 13
df_applications.loc[df_applications['Окончание'] == "Сабетта 2 ", 'Окончание'] = 12
df_applications.loc[df_applications['Окончание'] == "Сабетта 3 ", 'Окончание'] = 10
df_applications.loc[df_applications['Окончание'] == "Саббета 1", 'Окончание'] = 13
df_applications.loc[df_applications['Окончание'] == "Саббета 2", 'Окончание'] = 12
df_applications.loc[df_applications['Окончание'] == "Саббета 3", 'Окончание'] = 10
df_applications.loc[df_applications['Окончание'] == "Саббета 1 ", 'Окончание'] = 13
df_applications.loc[df_applications['Окончание'] == "Саббета 2 ", 'Окончание'] = 12
df_applications.loc[df_applications['Окончание'] == "Саббета 3 ", 'Окончание'] = 10

In [452]:
df_applications

IMO Ледовый класс Скорость Начало Окончание Дата и время начала  \
0   9752084             3       15      0        10      01.01.21 23:30   
1   9752084             3       15     10         0      06.01.21 11:00   
2   9752084             3       15      0        10      12.01.21 18:00   
3   9752084             3       15     10         0       17.01.21 6:00   
4   9752084             3       15      0        10       21.01.21 9:00   
5   9752084             3       15     10         0       28.01.21 1:00   
6   9759939             3       15     10         0      02.01.21 20:30   
7   9759939             3       15      0        10      07.01.21 19:00   
8   9759939             3       15     10         0      13.01.21 16:00   
9   9759939             3       15      0        10      17.01.21 13:00   
10  9759939             3       15     10         0       22.01.21 7:30   
11  9759939             3       15      0        10       28.01.21 2:00   
12  9194012             2       15      0        10      27.12.20 23:00   
13  9194012             2       15     10         0      20.01.21 15:00   
14  9837547             3       15     12         0      14.01.21 22:00   
15  9837547             3       15      0        12      19.01.21 12:00   
16  9804033             3       14     13         0       07.01.21 0:00   
17  9804033             3       14      0        13      26.01.21 22:00   
18  9750696             3       19      0        13      01.01.21 17:30   
19  9750696             3       19     13         0      07.01.21 17:00   
20  9768394             3       19      0        13      08.01.21 22:00   
21  9750737             3       19      0        13      16.01.21 18:00   
22  9750737             3       19     13         0      26.01.21 10:00   
23  9750701             3       19     13         0       01.01.21 0:00   
24  9243801             2       14      0        12       13.01.21 1:30   
25  9243801             2       14     12         0      24.01.21 21:00   
26  8711289             2       15     12         0      29.12.20 15:00   
27  8711289             2       15      0        13       09.01.21 3:00   
28  8711289             2       15     13         0       19.01.21 4:00   
29  9267297             2       14     12         0      05.01.21 21:00   
30  9267297             2       14      0        12      24.01.21 10:00   
31  9202053             2       12      0        12       23.01.21 0:30   
32  9366110             2       16      0        12      31.12.20 12:00   
33  9366110             2       16     12         0     16.01.021 12:30   
34  9366110             2       16      0        12      29.01.21 10:00   
35  9014896             2       14      0        12       16.01.21 3:00   
36  9014896             2       14     12         0       22.01.21 3:00   
37  9834313             1       18      0        13      02.01.21 12:30   
38  9834313             1       18     13         0      04.01.21 11:00   
39  9834313             1       18      0        13       16.01.21 9:00   
40  9834313             1       18     13         0       20.01.21 9:00   
41  9834296             1       16      0        13       02.01.21 0:30   
42  9834296             1       16     13         0      06.01.21 15:00   
43  9834296             1       16      0        13      12.01.21 10:00   
44  9834296             1       16     13         0      13.01.21 19:30   
45  9834296             1       16      0        13       22.01.21 7:00   
46  9834296             1       16     13         0       23.01.21 0:30   

     Дата и время окончания  
0             05.01.21 5:00  
1            10.01.21 18:00  
2            16.01.21 22:00  
3            21.01.21 20:45  
4            26.01.21 22:00  
5            02.02.21 19:00  
6             06.01.21 7:00  
7             11.01.21 3:20  
8            17.01.21 14:00  
9            21.01.21 16:20  
10           26.01.21 19:00  
11           03.02.21 19:00  
12           07.0

In [453]:
df_applications["Дата и время начала"][33] = "16.01.21 12:30"
df_applications["Дата и время окончания"][34] = "01.02.21 23:30"
df_applications

IMO Ледовый класс Скорость Начало Окончание Дата и время начала  \
0   9752084             3       15      0        10      01.01.21 23:30   
1   9752084             3       15     10         0      06.01.21 11:00   
2   9752084             3       15      0        10      12.01.21 18:00   
3   9752084             3       15     10         0       17.01.21 6:00   
4   9752084             3       15      0        10       21.01.21 9:00   
5   9752084             3       15     10         0       28.01.21 1:00   
6   9759939             3       15     10         0      02.01.21 20:30   
7   9759939             3       15      0        10      07.01.21 19:00   
8   9759939             3       15     10         0      13.01.21 16:00   
9   9759939             3       15      0        10      17.01.21 13:00   
10  9759939             3       15     10         0       22.01.21 7:30   
11  9759939             3       15      0        10       28.01.21 2:00   
12  9194012             2       15      0        10      27.12.20 23:00   
13  9194012             2       15     10         0      20.01.21 15:00   
14  9837547             3       15     12         0      14.01.21 22:00   
15  9837547             3       15      0        12      19.01.21 12:00   
16  9804033             3       14     13         0       07.01.21 0:00   
17  9804033             3       14      0        13      26.01.21 22:00   
18  9750696             3       19      0        13      01.01.21 17:30   
19  9750696             3       19     13         0      07.01.21 17:00   
20  9768394             3       19      0        13      08.01.21 22:00   
21  9750737             3       19      0        13      16.01.21 18:00   
22  9750737             3       19     13         0      26.01.21 10:00   
23  9750701             3       19     13         0       01.01.21 0:00   
24  9243801             2       14      0        12       13.01.21 1:30   
25  9243801             2       14     12         0      24.01.21 21:00   
26  8711289             2       15     12         0      29.12.20 15:00   
27  8711289             2       15      0        13       09.01.21 3:00   
28  8711289             2       15     13         0       19.01.21 4:00   
29  9267297             2       14     12         0      05.01.21 21:00   
30  9267297             2       14      0        12      24.01.21 10:00   
31  9202053             2       12      0        12       23.01.21 0:30   
32  9366110             2       16      0        12      31.12.20 12:00   
33  9366110             2       16     12         0      16.01.21 12:30   
34  9366110             2       16      0        12      29.01.21 10:00   
35  9014896             2       14      0        12       16.01.21 3:00   
36  9014896             2       14     12         0       22.01.21 3:00   
37  9834313             1       18      0        13      02.01.21 12:30   
38  9834313             1       18     13         0      04.01.21 11:00   
39  9834313             1       18      0        13       16.01.21 9:00   
40  9834313             1       18     13         0       20.01.21 9:00   
41  9834296             1       16      0        13       02.01.21 0:30   
42  9834296             1       16     13         0      06.01.21 15:00   
43  9834296             1       16      0        13      12.01.21 10:00   
44  9834296             1       16     13         0      13.01.21 19:30   
45  9834296             1       16      0        13       22.01.21 7:00   
46  9834296             1       16     13         0       23.01.21 0:30   

   Дата и время окончания  
0           05.01.21 5:00  
1          10.01.21 18:00  
2          16.01.21 22:00  
3          21.01.21 20:45  
4          26.01.21 22:00  
5          02.02.21 19:00  
6           06.01.21 7:00  
7           11.01.21 3:20  
8          17.01.21 14:00  
9          21.01.21 16:20  
10         26.01.21 19:00  
11         03.02.21 19:00  
12         07.01.21 17:00  
13         30.0

In [454]:
from datetime import datetime

date_zero = datetime(2020, 1, 1, 0, 0, 0)
days_of_start=[]
days_of_finish=[]
for i in range(47):
    date = datetime.strptime(df_applications["Дата и время начала"][i], "%d.%m.%y %H:%M")
    if date.day == 31: days_of_start.append(30)
    else: days_of_start.append(date.day)
    df_applications["Дата и время начала"][i] = (date-date_zero).total_seconds()
    
    
    date = datetime.strptime(df_applications["Дата и время окончания"][i], "%d.%m.%y %H:%M")
    if date.day == 31: days_of_finish.append(30)
    else: days_of_finish.append(date.day)
    df_applications["Дата и время окончания"][i] = (date-date_zero).total_seconds()

In [455]:
df_applications.insert(7, "Число начала",days_of_start)
df_applications.insert(7, "Число окончания",days_of_finish)

In [456]:
df_applications.head()

IMO Ледовый класс Скорость Начало Окончание Дата и время начала  \
0  9752084             3       15      0        10          31707000.0   
1  9752084             3       15     10         0          32094000.0   
2  9752084             3       15      0        10          32637600.0   
3  9752084             3       15     10         0          33026400.0   
4  9752084             3       15      0        10          33382800.0   

  Дата и время окончания  Число окончания  Число начала  
0             31986000.0                5             1  
1             32464800.0               10             6  
2             32997600.0               16            12  
3             33425100.0               21            17  
4             33861600.0               26            21

In [457]:
df_applications.describe()

Число окончания  Число начала
count        47.000000     47.000000
mean         15.127660     15.425532
std           9.293796      8.950940
min           1.000000      1.000000
25%           6.500000      7.000000
50%          16.000000     16.000000
75%          22.500000     22.500000
max          30.000000     30.000000

In [458]:
def get_time_alone_from_to(dot_from,speed,class_of_ship,day):
    graph_with_time=[]
    
    from_to_with_ib = [ 
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
    '''
    0 - можно самому
    1 - можно с ледоколом
    2 - нельзя
    '''
    
    
    for i in range(14):
        a=[]
        for j in range(14):
            if(graph_of_path[i][j]!=0):
                if(class_of_ship == 1 and ice_concentration[graph_of_path[i][j]-1][day]>6): 
                    from_to_with_ib[i][j] = 2
                    a.append(float("inf"))
                elif(class_of_ship == 1 and ice_concentration[graph_of_path[i][j]-1][day-1]<7 and ice_concentration[graph_of_path[i][j]-1][day-1]>3): 
                    from_to_with_ib[i][j] = 1
                    a.append(graph_with_lengths[i][j]/9)
                elif(class_of_ship == 2 and ice_concentration[graph_of_path[i][j]-1][day-1]>6): 
                    from_to_with_ib[i][j] = 1
                    a.append(graph_with_lengths[i][j]/9)
                else:
                    a.append(graph_with_lengths[i][j]/float(count_speed(float(speed),float(ice_concentration[graph_of_path[i][j]-1][day-1]))))
            else:
                a.append(0)
        graph_with_time.append(a)
        
    g = Graph(14)
    g.graph = graph_with_time

    time_of_ways = g.dijkstra(dot_from)
    return [from_to_with_ib, time_of_ways]

In [459]:
df_applications

IMO Ледовый класс Скорость Начало Окончание Дата и время начала  \
0   9752084             3       15      0        10          31707000.0   
1   9752084             3       15     10         0          32094000.0   
2   9752084             3       15      0        10          32637600.0   
3   9752084             3       15     10         0          33026400.0   
4   9752084             3       15      0        10          33382800.0   
5   9752084             3       15     10         0          33958800.0   
6   9759939             3       15     10         0          31782600.0   
7   9759939             3       15      0        10          32209200.0   
8   9759939             3       15     10         0          32716800.0   
9   9759939             3       15      0        10          33051600.0   
10  9759939             3       15     10         0          33463800.0   
11  9759939             3       15      0        10          33962400.0   
12  9194012             2       15      0        10          31273200.0   
13  9194012             2       15     10         0          33318000.0   
14  9837547             3       15     12         0          32824800.0   
15  9837547             3       15      0        12          33220800.0   
16  9804033             3       14     13         0          32140800.0   
17  9804033             3       14      0        13          33861600.0   
18  9750696             3       19      0        13          31685400.0   
19  9750696             3       19     13         0          32202000.0   
20  9768394             3       19      0        13          32306400.0   
21  9750737             3       19      0        13          32983200.0   
22  9750737             3       19     13         0          33818400.0   
23  9750701             3       19     13         0          31622400.0   
24  9243801             2       14      0        12          32664600.0   
25  9243801             2       14     12         0          33685200.0   
26  8711289             2       15     12         0          31417200.0   
27  8711289             2       15      0        13          32324400.0   
28  8711289             2       15     13         0          33192000.0   
29  9267297             2       14     12         0          32043600.0   
30  9267297             2       14      0        12          33645600.0   
31  9202053             2       12      0        12          33525000.0   
32  9366110             2       16      0        12          31579200.0   
33  9366110             2       16     12         0          32963400.0   
34  9366110             2       16      0        12          34077600.0   
35  9014896             2       14      0        12          32929200.0   
36  9014896             2       14     12         0          33447600.0   
37  9834313             1       18      0        13          31753800.0   
38  9834313             1       18     13         0          31921200.0   
39  9834313             1       18      0        13          32950800.0   
40  9834313             1       18     13         0          33296400.0   
41  9834296             1       16      0        13          31710600.0   
42  9834296             1       16     13         0          32108400.0   
43  9834296             1       16      0        13          32608800.0   
44  9834296             1       16     13         0          32729400.0   
45  9834296             1       16      0        13          33462000.0   
46  9834296             1       16     13         0          33525000.0   

   Дата и время окончания  Число окончания  Число начала  
0              31986000.0                5             1  
1              32464800.0               10             6  
2              32997600.0               16            12  
3              33425100.0               21            17  
4              33861600.0               26            21  
5              34455600.0                2           

In [460]:
idx=40
get_time_alone_from_to(0,df_applications['Скорость'][idx],df_applications['Ледовый класс'][idx],(df_applications['Число начала'][idx]+df_applications['Число окончания'][idx])//2)

Vertex 	 Distance from Source
0 		 0
1 		 47.932167119068346
2 		 113.96039923875773
3 		 111.85391510110539
4 		 97.64891536621991
5 		 40.15709848656363
6 		 124.26962013990057
7 		 131.21696701239617
8 		 139.77046084849542
9 		 10000000.0
10 		 10000000.0
11 		 10000000.0
12 		 10000000.0
13 		 10000000.0


[[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 1],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]],
 [0,
  47.932167119068346,
  113.96039923875773,
  111.85391510110539,
  97.64891536621991,
  40.15709848656363,
  124.26962013990057,
  131.21696701239617,
  139.77046084849542,
  10000000.0,
  10000000.0,
  10000000.0,
  10000000.0,
  10000000.0]]

In [463]:
ice_concentration[9][(df_applications['Число начала'][idx]+df_applications['Число окончания'][idx])//2]

7

In [464]:
df_applications['Ледовый класс'][idx]

1